### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'decryptWithDCKey'

### ISSUE THREAD

**Issue by psyray** [tijldeneut/DPAPIck3#6]
Hi,

I'm trying to use your example filegeneric.py.

I have correctly extracted the private domain key using [DSInternals](https://github.com/MichaelGrafnetter/DSInternals/blob/master/Documentation/PowerShell/Get-ADDBBackupKey.md) command, it generates `pvk` file.

I have the Master key and the SID, but when I launch the command
```sh
python3 ~/filegeneric.py --sid S-1-5-21-xxx-xxx-xxx-500 --masterkey AppData/Roaming/Microsoft/Protect/S-1-5-21-xxx-xxx-xxx-500 --pkey ntds_capi_xxx-xxx-xxx-xxx-xxx.pvk --debug
```
I'm facing this error
```
Traceback (most recent call last):
  File "/xxx/lib/python3.10/site-packages/dpapick3/masterkey.py", line 536, in try_domain
    try: mk.domainkey.decryptWithDCKey(privkeyfile)
AttributeError: 'NoneType' object has no attribute 'decryptWithDCKey'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/xxx/filegeneric.py", line 80, in <module>
    decrn = mkp.try_domain(options.pkey)
  File "/xxx/python3.10/site-packages/dpapick3/masterkey.py", line 537, in try_domain
    except: mk.domainkey.decryptWithPVKKey(privkeyfile)
AttributeError: 'NoneType' object has no attribute 'decryptWithPVKKey'
```

First I've tried using [dpapiclab-ng](https://github.com/tijldeneut/dpapilab-ng), which uses your lib, but same error.
The I tried directly yours to be sure that the identify problem source.

Do you know where it could comes ?

**Comment by psyray** [comment]
Found the problem, it misses a domain key check here :
https://github.com/tijldeneut/DPAPIck3/blob/111795e80f2251a4932dc177236ae10e1d4ca3e5/dpapick3/masterkey.py#L535C28-L535C28

Check if  **domainkey** is not empty (it was my case)
```python
if not mk.decrypted and mk.domainkey:
```

**Comment by tijldeneut** [comment]
You are right, that is a small bug fix, thank you for the update:
https://github.com/tijldeneut/DPAPIck3/commit/fea584df190ce48a1d7b7c8a1a19d4dd044ec6f5
I will incorporate it into the pypi package DPAPICK3 as soon as I get the chance.
