### ISSUE TITLE
Installing DPAPIck3 offline; unicodecsv requires setuptools>=40.8.0, still gives same error even if setuptools 75.1.0 is installed

### ISSUE THREAD

**Issue by InfiniteBSOD** [tijldeneut/DPAPIck3#8]
Hello,

Trying to install dpapick3 v. 0.5.1 from pip on an offline machine.
Running into problems when satisfying the dependencies for dpapick3.

Please see below:

```
Host (with internet): Windows 11 

Python 3.12.5
pip download DPAPIck3

dpapick3-0.5.1-py3-none-any.whl
enum_compat-0.0.3-py3-none-any.whl
pyasn1-0.6.1-py3-none-any.whl
pycryptodome-3.20.0-cp35-abi3-win_amd64.whl
python_registry-1.3.1-py3-none-any.whl
unicodecsv-0.14.1.tar.gz

Guest (without internet): Windows 11

Python 3.12.6
pip install .\dpapick3-0.5.1-py3-none-any.whl
^ Requires "pycryptodome"
pip install .\pycryptodome-3.20.0-cp35-abi3-win_amd64.whl
^ Works
pip install .\dpapick3-0.5.1-py3-none-any.whl
^ Requires "python-registry"
pip install .\python_registry-1.3.1-py3-none-any.whl
^ Requires "enum-compat"
pip install .\enum_compat-0.0.3-py3-none-any.whl
^ Works
pip install .\python_registry-1.3.1-py3-none-any.whl
^ Requires "unicodecsv"
pip install .\unicodecsv-0.14.1.tar.gz
^ ERROR: Could not find a version that satisfies the requirement setuptools>=40.8.0 (from versions: none)
ERROR: No matching distribution found for setuptools>=40.8.0
^ Downloaded "setuptools-75.1.0-py3-none-any.whl"
pip install .\setuptools-75.1.0-py3-none-any.whl
^ Works
pip install .\unicodecsv-0.14.1.tar.gz
^ ERROR: Could not find a version that satisfies the requirement setuptools>=40.8.0 (from versions: none)
ERROR: No matching distribution found for setuptools>=40.8.0

"pip list" returns:
setuptools 75.1.0
```

So the requirement of setuptools being greater or equal than the version 40.8.0 should be satisfied but I am still receiving the error:
```
ERROR: Could not find a version that satisfies the requirement setuptools>=40.8.0 (from versions: none)
ERROR: No matching distribution found for setuptools>=40.8.0
```

Any ideas on why?

Best Regards

**Comment by tijldeneut** [comment]
The issue is the fact that "unicodecsv" is a tar.gz-file. This means it has not been compiled and needs to be build locally.
For this the setuptools are needed and the wheel package.
Creation of the files and easy installation on an online system, make sure to run this in an empty folder:
```
pip download dpapick3 wheel setuptools 
dir /b > requirements.txt
```

Offline installation:
```
pip install -r requirements.txt
```

Kind Regards

**Comment by InfiniteBSOD** [comment]
> The issue is the fact that "unicodecsv" is a tar.gz-file. This means it has not been compiled and needs to be build locally. For this the setuptools are needed and the wheel package. Creation of the files and easy installation on an online system, make sure to run this in an empty folder:
> 
> ```
> pip download dpapick3 wheel setuptools 
> dir /b > requirements.txt
> ```
> 
> Offline installation:
> 
> ```
> pip install -r requirements.txt
> ```
> 
> Kind Regards

Thanks!
Worked perfectly.

Just an addition:
`dir /b > requirements.txt` only works in CMD, for PowerShell (while in the directory where the files  are downloaded):
`Get-ChildItem -Path . | Select-Object -ExpandProperty Name > requirements.txt`
